export const LIKE_BUTTON_PRESSED = 'like_button_pressed'
export const POLL_OPTION_PRESSED = 'poll_option_pressed'
export const GO_TO_POST = 'go_to_post'
export const COMMENT_SUBMITTED = 'comment_submitted'
export const COMMENT_LIKE_BUTTON_PRESSED = 'comment_like_button_pressed'
