export const LIKE_BUTTON_PRESSED = 'like_button_pressed'
export const POLL_OPTION_PRESSED = 'poll_option_pressed'
export const DETAIL_SELECTED = 'detail_selected'
export const COMMENT_SUBMITTED = 'comment_submitted'
export const COMMENT_LIKE_BUTTON_PRESSED = 'comment_like_button_pressed'
export const RATE_STAR_PRESSED = 'rate_star_pressed'
